os:
  - linux

language: python
python:
  - "2.7"

branches:
  only:
    - travis



install:
  - "python setup.py bdist_wheel"
  - "pip install --pre --no-index --find-links dist/ portal"


# command to run tests
script:
  - "python test/test_basic.py"
  - "python test/test_operators.py"
