os:
  - linux

language: python
python:
  - "2.7"

branches:
  only:
    - travis



install:
  - "python setup.py bdist_wheel"
  - "pip install --no-index --pre --find-links dist/ portal"


# command to run tests
script:
  - "cd test/"
  - "python test_basic.py"
  - "python test_operators.py"
