os:
  - linux

language: python
python:
  - "2.7"


install:
  - "python setup.py bdist_wheel"
  - "pip install --find-links dist/ portal"


# command to run tests
script:
  - "python test/test_all.py"
